-- 예소 초기 스키마. "ERD.md" 3장 테이블 목록과 4장 제약조건·인덱스를 그대로 옮긴다.
--
-- 시각 컬럼은 전부 timestamptz 를 쓴다. "ERD.md" 5-2 가 확정한 표준 UTC 방식이며,
-- 서버는 UTC 로 저장하고 앱과 기기가 표시 시점에 KST 로 바꾼다.
-- 반면 start_time / end_time 은 time 을 쓴다. 이 값은 "KST 벽시계 시각" 이라서
-- 아침 8시 30분에 일어난다는 약속이 시간대를 옮겨도 아침 8시 30분이어야 하기 때문이다.
--
-- 문자열 길이 상한은 걸지 않는다. "ERD.md" 가 길이를 정하지 않았고,
-- 임의로 정한 상한은 나중에 실제 데이터가 넘칠 때 조용히 저장 실패를 낸다.

-- ---------------------------------------------------------------------------
-- 계정
-- ---------------------------------------------------------------------------

create table users (
    id               bigint generated by default as identity primary key,
    provider         varchar     not null,
    provider_user_id varchar     not null,
    -- 소셜 로그인 직후에는 아직 성명을 받기 전이라 비어 있다.
    -- 온보딩 1차에서 채운다.
    name             varchar,
    email            varchar,
    created_at       timestamptz not null default now(),
    deleted_at       timestamptz
);

-- 같은 소셜 계정으로 두 번 가입하는 것을 막는다.
-- 소셜 로그인은 "찾거나 없으면 만든다" 로 동작하므로 이 제약이 그 근거가 된다.
create unique index users_provider_and_provider_user_id_unique
    on users (provider, provider_user_id);

create table children (
    id           bigint generated by default as identity primary key,
    user_id      bigint      not null references users (id),
    name         varchar     not null,
    birth_date   date,
    -- 보호자와 자녀의 관계. enum 을 쓰기로 확정했지만 값 목록이 아직 정해지지
    -- 않아서(ROADMAP 0-4) DB 에는 검사 제약을 걸지 않는다. 값이 확정되면
    -- 그때 check 제약을 추가한다.
    relationship varchar,
    deleted_at   timestamptz
);

create index children_user_id_index on children (user_id);

-- ---------------------------------------------------------------------------
-- 기기
-- ---------------------------------------------------------------------------

create table devices (
    id                      bigint generated by default as identity primary key,
    child_id                bigint      not null references children (id),
    -- 앱과 기기를 잇는 식별자. 기기에서 만들어 claim 때 보내온다.
    device_uid              varchar     not null,
    -- 토큰과 비밀값은 평문으로 두지 않는다. 발급하는 순간에만 평문을 응답에 담고
    -- DB 에는 해시만 남긴다. secret 은 재페어링 없이 토큰을 복구하는 유일한
    -- 경로에 쓰이므로 반드시 필요하다.
    token_hash              varchar,
    secret_hash             varchar,
    -- 페어링 코드는 claim 이 끝나면 null 로 지운다. 일회용이기 때문이다.
    pairing_code            varchar,
    pairing_code_expires_at timestamptz,
    status                  varchar     not null,
    nickname                varchar,
    battery_level           int,
    firmware_version        varchar,
    last_synced_at          timestamptz,
    paired_at               timestamptz,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now(),
    deleted_at              timestamptz
);

-- 살아 있는 행끼리만 device_uid 가 유일하다.
-- "where deleted_at is null" 이 이 인덱스의 핵심이다. 이 조건이 빠지면
-- 한 번 연결을 해제한 기기를 영원히 다시 연결할 수 없게 된다.
-- 게다가 평소에는 아무 문제가 없어서, 실제로 누가 재페어링을 시도할 때까지
-- 아무도 알아차리지 못한다.
create unique index devices_device_uid_unique_when_not_deleted
    on devices (device_uid)
    where deleted_at is null;

-- PENDING 인 행끼리만 페어링 코드가 유일하다.
-- claim 은 코드 하나로 행 하나를 특정해야 하므로 중복이 있으면 안 된다.
-- 이미 사용된 코드는 null 로 지워지므로 조건에서 자연히 빠진다.
create unique index devices_pairing_code_unique_when_pending
    on devices (pairing_code)
    where status = 'PENDING';

-- 자녀 기기 목록 조회용. 해제된 기기를 걸러내며 조회하므로 deleted_at 을 함께 넣는다.
create index devices_child_id_and_deleted_at_index on devices (child_id, deleted_at);

-- child_id 단독 유니크 제약은 "만들지 않는다".
-- 기획이 자녀 1명당 기기 1대에서 N 대로 바뀌었기 때문이다.
-- 이 제약이 남아 있으면 두 번째 기기 등록이 막힌다.

-- ---------------------------------------------------------------------------
-- 루틴
-- ---------------------------------------------------------------------------

create table routine_templates (
    id             bigint generated by default as identity primary key,
    child_id       bigint      not null references children (id),
    title          varchar     not null,
    start_time     time,
    end_time       time,
    -- 템플릿에 딸린 할 일 목록. 행으로 쪼개지 않고 jsonb 한 칸에 담는다.
    -- 이 값은 빅루틴을 만들 때 통째로 복사되는 원본이라 따로 조회하거나
    -- 수정할 일이 없기 때문이다. jsonb 사용이 PostgreSQL 을 고른 이유이기도 하다.
    small_routines jsonb,
    is_active      boolean     not null default true,
    deleted_at     timestamptz
);

create index routine_templates_child_id_index on routine_templates (child_id);

create table big_routines (
    id           bigint generated by default as identity primary key,
    child_id     bigint      not null references children (id),
    -- 템플릿에서 자동 생성된 루틴이면 원본을 가리키고, 직접 만든 루틴이면 비어 있다.
    template_id  bigint      references routine_templates (id),
    -- "이 루틴들이 원래 같은 미션인가" 를 표시하는 값. 미션별 이행률 집계의 기준이다.
    series_id    uuid,
    routine_date date        not null,
    title        varchar     not null,
    start_time   time,
    end_time     time,
    sort_order   int,
    deleted_at   timestamptz
);

-- 같은 템플릿에서 같은 날짜의 루틴이 두 번 만들어지는 것을 막는다.
-- 지연 생성을 부르는 지점이 세 곳(routines / calendar / sync)이라 동시에
-- 호출되면 중복이 생길 수 있다. 애플리케이션 코드로 막기 어려운 경합이라
-- DB 제약이 마지막 방어선이 된다.
create unique index big_routines_template_id_and_routine_date_unique_when_not_deleted
    on big_routines (template_id, routine_date)
    where deleted_at is null;

-- 날짜별 조회와 캘린더 조회용
create index big_routines_child_id_and_routine_date_index on big_routines (child_id, routine_date);

-- 미션별 이행률 집계용
create index big_routines_series_id_index on big_routines (series_id);

create table small_routines (
    id            bigint generated by default as identity primary key,
    big_routine_id bigint     not null references big_routines (id),
    series_id     uuid,
    title         varchar     not null,
    sort_order    int,
    status        varchar     not null,
    completed_at  timestamptz,
    deleted_at    timestamptz
);

-- 빅루틴 안에서 정해진 순서대로 꺼내오기 위한 인덱스
create index small_routines_big_routine_id_and_sort_order_index
    on small_routines (big_routine_id, sort_order);

create index small_routines_series_id_index on small_routines (series_id);

-- ---------------------------------------------------------------------------
-- 캐릭터
-- ---------------------------------------------------------------------------

create table characters (
    id        bigint generated by default as identity primary key,
    code      varchar not null,
    name      varchar not null,
    -- 획득 희귀도와 가중치. 실제로 쓸지가 아직 정해지지 않았지만(ROADMAP 0-5)
    -- "ERD.md" 가 컬럼을 유지하고 있어 그대로 만든다. 값이 없어도 되도록 열어둔다.
    rarity    varchar,
    weight    int,
    -- 캐릭터 이미지의 S3 키를 담는다. URL 은 읽을 때 조립한다.
    assets    jsonb,
    -- 캐릭터는 지우지 않고 이 값으로 도감에서 감춘다
    is_active boolean not null default true
);

create unique index characters_code_unique on characters (code);

create table child_characters (
    id           bigint generated by default as identity primary key,
    child_id     bigint      not null references children (id),
    character_id bigint      not null references characters (id),
    level        int         not null default 1,
    exp          int         not null default 0,
    acquired_at  timestamptz not null default now()
);

create index child_characters_child_id_index on child_characters (child_id);

-- ---------------------------------------------------------------------------
-- 커뮤니티
--
-- 이 도메인은 API 를 구현하지 않기로 했다("ERD.md" 5-5 / 5-6).
-- 그럼에도 테이블을 만들어 두는 이유는 "ERD.md" 3장이 정의를 유지하기로 했고,
-- 운영 중인 DB 에 나중에 테이블을 추가하는 비용이 지금 만들어두는 비용보다
-- 훨씬 크기 때문이다. 아래 테이블을 읽거나 쓰는 코드는 만들지 않는다.
-- ---------------------------------------------------------------------------

create table posts (
    id            bigint generated by default as identity primary key,
    user_id       bigint      not null references users (id),
    title         varchar     not null,
    content       text,
    -- 매번 세지 않기 위해 미리 세어 둔 값. 갱신 시점은 아직 정해지지 않았다.
    like_count    int         not null default 0,
    comment_count int         not null default 0,
    created_at    timestamptz not null default now(),
    deleted_at    timestamptz
);

create table comments (
    id                bigint generated by default as identity primary key,
    post_id           bigint      not null references posts (id),
    user_id           bigint      not null references users (id),
    -- 자기 자신을 가리켜 1단계 대댓글을 만든다. 최상위 댓글이면 비어 있다.
    parent_comment_id bigint      references comments (id),
    content           text,
    deleted_at        timestamptz
);

create index comments_post_id_index on comments (post_id);

create table post_likes (
    id         bigint generated by default as identity primary key,
    post_id    bigint      not null references posts (id),
    user_id    bigint      not null references users (id),
    created_at timestamptz not null default now()
);

-- 한 사람이 같은 글에 좋아요를 두 번 누르는 것을 막는다
create unique index post_likes_post_id_and_user_id_unique on post_likes (post_id, user_id);
